from __future__ import annotations
from typing import Iterable, Optional, Protocol
from .domain import Episode

class MangaRepository(Protocol):
    # ---- Nuevo: lista IDs de mangas
    def list_mangas(self) -> Iterable[str]: ...
    def list_episodes(self, manga_id: str) -> Iterable[Episode]: ...
    def get_episode_by_id(self, manga_id: str, episode_id: str) -> Optional[Episode]: ...
    def get_episode_by_number(self, manga_id: str, number: int) -> Optional[Episode]: ...

class S3PresignService(Protocol):
    def presign_get(self, key: str, expires: int = 900) -> str: ...
