from __future__ import annotations
from typing import Iterable, Optional, Protocol
from .domain import Manga, Chapter

class MangaRepository(Protocol):
    # Mangas
    def list_mangas(self) -> Iterable[Manga]: ...
    def manga_exists(self, manga_id: str) -> bool: ...

    # Chapters
    def list_chapters(self, manga_id: str) -> Iterable[Chapter]: ...
    def get_chapter_by_id(self, manga_id: str, chapter_id: str) -> Optional[Chapter]: ...
    def get_chapter_by_number(self, manga_id: str, number: int) -> Optional[Chapter]: ...

class S3PresignService(Protocol):
    def presign_get(self, key: str, expires: int = 900) -> str: ...
