from __future__ import annotations
from typing import Iterable, Optional, Protocol
from .domain import Manga, Chapter

class MangaRepository(Protocol):
    # Mangas
    def list_mangas(self) -> Iterable[Manga]: ...
    def manga_exists(self, manga_id: str) -> bool: ...
    def get_manga(self, manga_id: str) -> Optional[Manga]: ...
    def create_manga(self, manga: Manga) -> Manga: ...

    # Chapters
    def list_chapters(self, manga_id: str) -> Iterable[Chapter]: ...
    def get_chapter_by_id(self, manga_id: str, chapter_id: str) -> Optional[Chapter]: ...
    def get_chapter_by_number(self, manga_id: str, number: int) -> Optional[Chapter]: ...
    def create_chapter(self, chapter: Chapter) -> Chapter: ...

class S3PresignService(Protocol):
    def presign_get(self, key: str, expires: int = 900, content_type: str = None, inline: bool = True) -> str: ...
    def presign_put(self, key: str, content_type: str = "application/pdf", expires: int = 900) -> str: ...

