name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Inku/Inku   # <-- carpeta donde está gradlew

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        with:
          build-root-directory: Inku/Inku   # <-- igual que arriba

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Sync & Verify
        run: ./gradlew --version

      - name: Lint & Static Analysis
        run: ./gradlew :app:ktlintCheck :app:detekt

      - name: Unit Tests (JUnit 5)
        run: ./gradlew :app:test

      - name: Assemble Debug
        run: ./gradlew :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: Inku/app/build/outputs/apk/debug/*.apk  # <-- ruta con subcarpeta
